### ISSUE TITLE
ValueError: Unknown scheme for proxy URL URL('socks://localhost:10808/')

### ISSUE THREAD

**Issue by AImagicAI** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#134]
Hello, I encountered the following error while running Python demo/seed/app. py. How should I resolve it? Thank you·

Traceback (most recent call last):
  File "/home/cv8888/byf/industrial_vision/SAM/Segment-Everything-Everywhere-All-At-Once/demo/seem/app.py", line 14, in <module>
    import gradio as gr
  File "/home/cv8888/anaconda3/envs/efficientvit/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "/home/cv8888/anaconda3/envs/efficientvit/lib/python3.10/site-packages/gradio/_simple_templates/__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "/home/cv8888/anaconda3/envs/efficientvit/lib/python3.10/site-packages/gradio/_simple_templates/simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "/home/cv8888/anaconda3/envs/efficientvit/lib/python3.10/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/home/cv8888/anaconda3/envs/efficientvit/lib/python3.10/site-packages/gradio/components/annotated_image.py", line 14, in <module>
    from gradio.components.base import Component
  File "/home/cv8888/anaconda3/envs/efficientvit/lib/python3.10/site-packages/gradio/components/base.py", line 20, in <module>
    from gradio.blocks import Block, BlockContext
  File "/home/cv8888/anaconda3/envs/efficientvit/lib/python3.10/site-packages/gradio/blocks.py", line 29, in <module>
    from gradio import (
  File "/home/cv8888/anaconda3/envs/efficientvit/lib/python3.10/site-packages/gradio/networking.py", line 13, in <module>
    from gradio.routes import App  # HACK: to avoid circular import # noqa: F401
  File "/home/cv8888/anaconda3/envs/efficientvit/lib/python3.10/site-packages/gradio/routes.py", line 137, in <module>
    client = httpx.AsyncClient()
  File "/home/cv8888/anaconda3/envs/efficientvit/lib/python3.10/site-packages/httpx/_client.py", line 1429, in __init__
    proxy_map = self._get_proxy_map(proxies or proxy, allow_env_proxies)
  File "/home/cv8888/anaconda3/envs/efficientvit/lib/python3.10/site-packages/httpx/_client.py", line 217, in _get_proxy_map
    return {
  File "/home/cv8888/anaconda3/envs/efficientvit/lib/python3.10/site-packages/httpx/_client.py", line 218, in <dictcomp>
    key: None if url is None else Proxy(url=url)
  File "/home/cv8888/anaconda3/envs/efficientvit/lib/python3.10/site-packages/httpx/_config.py", line 336, in __init__
    raise ValueError(f"Unknown scheme for proxy URL {url!r}")
ValueError: Unknown scheme for proxy URL URL('socks://localhost:10808/')

**Comment by jwyang** [comment]
you probably need to upgrade/change the gradio version.
