### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by wangxinyu6666** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#25]
when I run the app.py script, the error is as follows below, and how I can run successfully, Thank you.

```
Traceback (most recent call last):
  File "D:\Projects\Segment-Everything-Everywhere-All-At-Once\demo_code\app.py", line 18, in <module>
    import whisper
  File "D:\Applications\Anaconda3\envs\seem\lib\site-packages\whisper.py", line 69, in <module>
    libc = ctypes.CDLL(libc_name)
  File "D:\Applications\Anaconda3\envs\seem\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by MaureenZOU** [comment]
Thanks so much for your interests. It seems the error is coming from whisper. https://github.com/openai/whisper
Also it is not recommend to run on macos and windows machine, as it does not have cuda enabled gpus or the package installation would be very different.
