### ISSUE TITLE
No such file or directory:Segment-Everything-Everywhere-All-At-Once-main/demo_code/null

### ISSUE THREAD

**Issue by MrKenknight** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#38]
I have a problem with this, can you explain it to me?

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/nts1/miniconda3/envs/SEEM/lib/python3.9/site-packages/starlette/responses.py", line 335, in __call__
    stat_result = await anyio.to_thread.run_sync(os.stat, self.path)
  File "/home/nts1/miniconda3/envs/SEEM/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/nts1/miniconda3/envs/SEEM/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/nts1/miniconda3/envs/SEEM/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
FileNotFoundError: [Errno 2] No such file or directory: '/home/nts1/users/tungdd7/Segment-Everything-Everywhere-All-At-Once-main/demo_code/null'

**Comment by jwyang** [comment]
@MrKenknight , thanks for rasing the issue! Could you try to upgrade your gradio to 3.31.0?

**Comment by Fabulani** [comment]
Had the same problem. Upgrading to gradio 3.31.0 fixed the issue.

**Comment by jwyang** [comment]
great!
