### ISSUE TITLE
"KeyError: 'dataset'"  when load the page

### ISSUE THREAD

**Issue by earlysleepearlyup** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#59]
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.8/dist-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.8/dist-packages/gradio/routes.py", line 291, in api_info
    return gradio.blocks.get_api_info(config, serialize)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 528, in get_api_info
    serializer = serializing.COMPONENT_MAPPING[type]()
KeyError: 'dataset'
```

my Environment:
gradio==3.31.0
pytorch==2.0.0
python==3.8.10

when I modify the version to 'gradio==3.30.0', there's no text error log. But I get this result below:
![image](https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/assets/29350259/ccb3b004-6c9c-4a94-9705-b42019b09bb5)

**Comment by reesekneeland** [comment]
Having the same error, installing the packages for this repository is a nightmare with endless conflicts, and once I get the conflicts resolved I get the same behavior described above.

**Comment by MaureenZOU** [comment]
As refer to https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11855

try:
`pip install gradio_client==0.2.7`

**Comment by reesekneeland** [comment]
Nope, I still get the mysterious error in the right side panels of the gradio app, with no console output.

**Comment by Masumathi** [comment]
I changed the version to "gradio==3.37.0" and it worked.

**Comment by tangyipeng100** [comment]
> As refer to [AUTOMATIC1111/stable-diffusion-webui#11855](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11855)
> 
> try: `pip install gradio_client==0.2.7`

It works!!!  thx!!!!!!!!!!!!!!!!!!!!

**Comment by Luodian** [comment]
> As refer to [AUTOMATIC1111/stable-diffusion-webui#11855](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11855)
> 
> try: `pip install gradio_client==0.2.7`

interesting and thanks a lot, my repo also gets this error after upgrading `gradio_client`.
